### ISSUE TITLE
Is this ready to use in our exercises?

### ISSUE THREAD

**Issue by pattonw** [dlmbl/dlmbl-unet#14]
* dlmbl-unet version: main branch
* Python version: 3.11.9
* Operating System: MacOS

### Description

Use dlmbl_unet

### What I Did

pip install. This downgraded torch:
```
 - torch==2.3.1
 + torch==2.2.0
 - torchvision==0.18.1
 + torchvision==0.17.0
 ```
 Is this downgrade important?
 
 Added dependency from github `dlmbl_unet = git @ https://github.com/dlmbl-unet` to my `requirements.txt`. There are banners on the README that indicate the intention is to publish to pypi. Is there anything blocking this currently?

**Comment by pattonw** [comment]
importing also means this code will not be accessible to the students who may want to play around with / modify the UNet. Would it be better to include this library as a git submodule, then install it in editable mode in the `setup.sh` script?
I think this would make it easier for the students to inspect the code they are using and debug in the cases where they pass in invalid arguments

**Comment by neptunes5thmoon** [comment]
I think initially the intention was to publish to pypi but I don't wanna be in charge of a dlmbl pypi account (but that is where it should live). so tbd if we have time to convince the bosses to set that up.

They should be familiar with the UNet from the unet exercise and importing will make it easier to also use in the project phase, so I'm tending towards keeping it as a normal import. If someone is advanced enough that they wanna modify the UNet further I think they can figure out how to drop it in from the exercise or this library.

As for the downgrade I think it's TBD whether we need that... iirc this is currently there due to the hardware in Milan. So will have to test once we have the TA machines.

**Comment by neptunes5thmoon** [comment]
And yes, it's ready to use in exercises :)

**Comment by pattonw** [comment]
You don't necessarily need to be in charge of the DLMBL pypi account. You just need to get one of the bosses to create the account, and add a pypi api key to the organization. Then you can publish via a github action that has access to the token.

**Comment by neptunes5thmoon** [comment]
yes :) but that requires one of the bosses to have time to do that. Might be a prep day type of task

**Comment by neptunes5thmoon** [comment]
I removed the pin for now

**Comment by neptunes5thmoon** [comment]
tracking pypi publication in #17
